# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_auto_20161222_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='prenom',
            field=models.CharField(default='Unknow', max_length=31),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
