# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170509_1507'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='articlesTag',
        ),
        migrations.AddField(
            model_name='profile',
            name='articlesTag',
            field=models.ManyToManyField(related_name='user_tag', through='blog.UserTagArticle', to='blog.Article'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
