# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161027_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
