# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161215_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to=b'/article'),
            preserve_default=False,
        ),
    ]
