# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170324_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
            preserve_default=False,
        ),
    ]
