# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-10 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_commentaire_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('nb_visit', models.IntegerField(default=1)),
            ],
        ),
    ]
