# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170518_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('blog.commenter_article', 'Commenter un article'), ('blog.liker_article', 'Like un article'))},
        ),
    ]
