# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170518_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='article',
        ),
    ]
