# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_commentaire_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('article.comment', 'Commenter un article'), ('article.like', 'Like un article'))},
        ),
    ]
