# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170521_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('article_add_comment', 'Commenter un article'), ('article_add_like', 'Like un article'))},
        ),
    ]
